### ISSUE TITLE
Invalid configuration found in "Configuring the Email Sending Module"

### ISSUE THREAD

**Issue by dewniMW** [wso2/docs-is#1042]
When trying out [1] following error log was observed during server startup.

`[2020-01-09 14:09:58,768] ERROR {org.wso2.config.mapper.TomlParser} - Unexpected 's', expected ', ", ''', """, a number, a boolean, a date/time, an array, or a table (line 38, column 11)
[2020-01-09 14:09:58,768]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Error parsing deployment configuration
	at org.wso2.config.mapper.TomlParser.parse(TomlParser.java:140)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:249)
	at org.wso2.config.mapper.ConfigParser.deploy(ConfigParser.java:217)
	at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigParser.java:180)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:127)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
	at org.wso2.carbon.server.Main.main(Main.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)`

This is due to an invalid configuration provided for hostname in step 2 of [1].
It should be corrected as:
`hostname= "smtp.gmail.com"`

[1] https://is.docs.wso2.com/en/5.9.0/setup/configuring-email-sending/#configuring-the-email-sending-module

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/1048.
